---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
  - name: task-repo
  - name: code-repo
    path: go/src/github.com/pivotal-cf/credhub-cli
run:
  path: task-repo/ci/tasks/unit-tests/task.sh
